# .gitpod.yml
image: gitpod/workspace-full

tasks:
  # 1) Download & unpack Julia into /workspace/julia-1.11.5
  - init: |
      curl -fsSL https://julialang-s3.julialang.org/bin/linux/x64/1.11/julia-1.11.5-linux-x86_64.tar.gz \
        | tar xz -C /workspace
      # instantiate & precompile in one go
      /workspace/julia-1.11.5/bin/julia --project=/workspace --startup-file=no \
        -e 'import Pkg; Pkg.instantiate(); Pkg.precompile()'
  # 2) Run your driver with the explicit path
  - command: |
      /workspace/julia-1.11.5/bin/julia --project=/workspace notebooks/driver.jl

