# .gitpod.yml
image: gitpod/workspace-full

tasks:
  # 1) Download & unpack Julia cleanly into /workspace/julia
  - init: |
      mkdir -p /workspace/julia
      curl -fsSL https://julialang-s3.julialang.org/bin/linux/x64/1.11/julia-1.11.5-linux-x86_64.tar.gz \
        | tar xz --strip-components=1 -C /workspace/julia

      # Install your project dependencies
      /workspace/julia/bin/julia --project=/workspace --startup-file=no \
        -e 'import Pkg; Pkg.instantiate(); Pkg.precompile()'

  # 2) Run your driver via the exact path
  - command: |
      /workspace/julia/bin/julia --project=/workspace notebooks/driver.jl
